- project:
    templates:
      - check-requirements
      - publish-openstack-sphinx-docs
      - openstack-python-jobs-horizon
      - openstack-python35-jobs-horizon
      - nodejs4-jobs
      - release-notes-jobs
    check:
      jobs:
        - openstack-tox-lower-constraints
        - horizon-openstack-tox-python3-django111
    gate:
      jobs:
        - openstack-tox-lower-constraints
        - horizon-openstack-tox-python3-django111
